### ISSUE TITLE
Call to a member function renderActiveForm() on null

### ISSUE THREAD

**Issue by dyar74** [skeeks-cms/cms#18]
добрый день!
После установки фронтенд ошибка: 
 PHP Fatal Error – yii\base\ErrorException
Call to a member function renderActiveForm() on null

    1. in /var/www/skeeks/vendor/skeeks/cms-module-form2/cmsWidgets/form2/views/whith-messages.php at line 74
    656667686970717273747576777879808182

            'class' => 'alert-danger sx-error-message',
            'style' => 'display: none;',
        ],
        'closeButton' => false,
        'body' => '<div class="sx-body">Ok</div>',
    ])?>
     
    <? if ($properties = $modelHasRelatedProperties->relatedProperties) : ?>
        <? foreach ($properties as $property) : ?>
            <?= $property->renderActiveForm($form, $modelHasRelatedProperties); ?>
        <? endforeach; ?>
    <? endif; ?>
     
    <?= \yii\helpers\Html::submitButton("" . \Yii::t('app', $widget->btnSubmit), [
        'class' => $widget->btnSubmitClass,
    ]); ?>
     
    <?php ActiveForm::end(); ?>

    2. yii\base\ErrorHandler::handleFatalError()

Бекенд логинишся и потом ошибка:
 PHP Fatal Error – yii\base\ErrorException
Call to a member function run() on null

    1. in /var/www/skeeks/vendor/skeeks/cms/modules/admin/views/index/dashboard.php at line 117
    108109110111112113114115116117118119120121122123124125126

                                                'actions'   => $actions,
     
                                                'options' =>
                                                [
                                                    'class' => 'sx-dashboard-widget',
                                                    'data'      => $cmsDashboardWidget->toArray(['id']),
                                                ],
                                            ]); ?>
                                                <? if ($cmsDashboardWidget->widget) : ?>
                                                    <?= $cmsDashboardWidget->widget->run(); ?>
                                                <? else : ?>
                                                    Виджет удален
                                                <? endif; ?>
                                            <? \skeeks\cms\modules\admin\widgets\AdminPanelWidget::end(); ?>
                                        <? endforeach; ?>
     
                                    <? endif; ?>
                                </td>
                                <? if ($dashboard->columns > 1 && $i != $dashboard->columns) : ?>

    2. yii\base\ErrorHandler::handleFatalError()

**Comment by skeeks-semenov** [comment]
@dyar74 Фронтенд часть поправил, можно перезалить https://github.com/skeeks-cms/cms-module-form2/tree/master/cmsWidgets/form2/views - вот это к себе, или же обновить зависимости composer

А по бэкенд не совсем понял, а другие страницы работают? your-site.ru/~sx/cms/admin-storage-files например

**Comment by dyar74** [comment]
Call to a member function isActive() on null
vendor/skeeks/cms/modules/admin/views/layouts/_admin-menu.php
<div class="sidebar-menu <?= $adminMenuItem->isActive() ? ' sx-opened' : '' ?>" id="<?= $adminMenuItem->code; ?>">

**Comment by skeeks-semenov** [comment]
@dyar74 Ок, скорее всего это настройки php 90%

http://en.cms.skeeks.com/docs/requirements
http://en.cms.skeeks.com/docs/install - 7й пункт, можно проверить.

Settings php:
**short_open_tag on**

**Comment by dyar74** [comment]
Да ошибка была в этом. Обычно эта директива в статусе off

**Comment by dyar74** [comment]
Спасибо!

**Comment by dyar74** [comment]
во фронте в футере выводится  Меню

    activeQuery->all()) : ?>

**Comment by skeeks-semenov** [comment]
@dyar74 Не совсем понимаю, можно скриншот?

**Comment by dyar74** [comment]
в футере в пункте меню было вместо меню activeQuery->all()) : ?>. Сейчас вроде норм. Спасибо
