### ISSUE TITLE
After installation, the installed page return error

### ISSUE THREAD

**Issue by fproject** [skeeks-cms/cms#19]
After installation using guideline at http://en.cms.skeeks.com/docs/install/installation-on-windows,
my page return this error:

> Error
> PHP Fatal Error – yii\base\ErrorException
> 
> Call to a member function renderActiveForm() on a non-object
> 1. in F:\GitRepo\demo.ru\vendor\skeeks\cms-module-form2\cmsWidgets\form2\views\with-messages.php at line 72
> 636465666768697071727374757677787980        'class' => 'alert-danger sx-error-message',
>         'style' => 'display: none;',
>     ],
>     'closeButton' => false,
>     'body' => '<div class="sx-body">Ok</div>',
> ])?>
>  
> <? if ($properties = $modelHasRelatedProperties->relatedProperties) : ?>
>     <? foreach ($properties as $property) : ?>
>         <?= $property->renderActiveForm($form, $modelHasRelatedProperties); ?>
>     <? endforeach; ?>
> <? endif; ?>
>  
> <?= \yii\helpers\Html::submitButton("" . \Yii::t('app', $widget->btnSubmit), [
>     'class' => $widget->btnSubmitClass,
> ]); ?>
>  
> <?php \skeeks\modules\cms\form2\widgets\ActiveFormConstructForm::end(); ?>
> 2. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 247 – yii\base\View::renderPhpFile()
> 3. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 149 – yii\base\View::renderFile()
> 4. in F:\GitRepo\demo.ru\vendor\skeeks\cms-module-form2\cmsWidgets\form2\views\whith-messages.php at line 16 – yii\base\View::render()
> 10111213141516 *
>  * TODO: this is derecated!!!
>  **/
> ?>
> <?= $this->render('with-messages', [
>     'widget' => $widget
> ])?>
> 5. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 325 – unknown()
> 6. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 247 – yii\base\View::renderPhpFile()
> 7. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 149 – yii\base\View::renderFile()
> 8. in F:\GitRepo\demo.ru\vendor\skeeks\cms\traits\WidgetTrait.php at line 177 – yii\base\View::render()
> 171172173174175176177178179180181182183     * @param array $params the parameters (name-value pairs) that should be made available in the view.
>      * @return string the rendering result.
>      * @throws InvalidParamException if the view file does not exist.
>      */
>     public function render($view, $params = [])
>     {
>         return $this->getView()->render($view, $params, $this);
>     }
>  
>     /**
>      * Renders a view file.
>      * @param string $file the view file to be rendered. This can be either a file path or a path alias.
>      * @param array $params the parameters (name-value pairs) that should be made available in the view.
> 9. in F:\GitRepo\demo.ru\vendor\skeeks\cms\base\WidgetRenderable.php at line 49 – skeeks\cms\base\Widget::render()
> 43444546474849505152535455    protected function _run()
>     {
>         if ($this->viewFile)
>         {
>             return $this->render($this->viewFile, [
>                 'widget' => $this
>             ]);
>         } else
>         {
>             return \Yii::t('app',"Template not found");
>         }
>     }
> }
> 10. in F:\GitRepo\demo.ru\vendor\skeeks\cms-module-form2\cmsWidgets\form2\FormWidget.php at line 114 – skeeks\cms\base\WidgetRenderable::_run()
> 108109110111112113114115116117 
>         if (!$this->modelForm)
>         {
>             return "";
>         }
>  
>         return parent::_run();
>     }
>  
> }
> 11. in F:\GitRepo\demo.ru\vendor\skeeks\cms\base\Widget.php at line 82 – skeeks\modules\cms\form2\cmsWidgets\form2\FormWidget::_run()
> 76777879808182838485868788            {
>                 $content = \Yii::t('app','Error widget {class}',['class' => $this->className()]). " (" . $this->descriptor->name . "): " . $e->getMessage();
>             }
>         } else
>         {
>             \Yii::beginProfile("Run: " . $this->_token);
>                 $content = $this->_run();
>             \Yii::endProfile("Run: " . $this->_token);
>         }
>  
>  
>         \Yii::$app->cmsToolbar->initEnabled();
>         if (\Yii::$app->cmsToolbar->editWidgets == Cms::BOOL_Y && \Yii::$app->cmsToolbar->enabled)
> 12. in F:\GitRepo\demo.ru\vendor\skeeks\cms\traits\WidgetTrait.php at line 91 – skeeks\cms\base\Widget::run()
> 85868788899091929394959697    {
>         ob_start();
>         ob_implicit_flush(false);
>         /* @var $widget Widget */
>         $config['class'] = get_called_class();
>         $widget = Yii::createObject($config);
>         $out = $widget->run();
>  
>         return ob_get_clean() . $out;
>     }
>  
>     private $_id;
>  
> 13. in F:\GitRepo\demo.ru\frontend\templates\default\footer.php at line 109 – skeeks\cms\base\Widget::widget()
> 103104105106107108109110111        <h2>Обратный звонок</h2>
>         <p>Оставьте ваш номер телефона и мы вам перезвоним.</p>
>         <?= \skeeks\modules\cms\form2\cmsWidgets\form2\FormWidget::widget([
>             'namespace' => 'FormWidget-all',
>             'form_code' => 'callback',
>             'viewFile' => 'whith-messages',
>         ])?>
>     </div>
> </div>
> 14. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 325 – unknown()
> 15. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 247 – yii\base\View::renderPhpFile()
> 16. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 149 – yii\base\View::renderFile()
> 17. in F:\GitRepo\demo.ru\frontend\templates\default\layouts\main.php at line 34 – yii\base\View::render()
> 28293031323334353637383940 
>         
>         <div class="body-wrap <?= \Yii::$app->templateBoomerang->bodyCssClasses; ?>">
>  
>             <?= $this->render('@app/views/header'); ?>
>                 <?= $content; ?>
>             <?= $this->render('@app/views/footer'); ?>
>  
>         </div>
>         
>  
>     <?php $this->endBody() ?>
> </body>
> 18. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 325 – unknown()
> 19. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\View.php at line 247 – yii\base\View::renderPhpFile()
> 20. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Controller.php at line 392 – yii\base\View::renderFile()
> 21. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Controller.php at line 378 – yii\base\Controller::renderContent()
> 22. in F:\GitRepo\demo.ru\vendor\skeeks\cms\base\Controller.php at line 64 – yii\base\Controller::render()
> 58596061626364656667686970        }
>  
>  
>         try
>         {
>             $viewApp = $this->beforeRender . $this->module->id . '/' . $this->id . '/' . $view;
>             return parent::render($viewApp, $params);
>  
>             /*$this->viewPath = $this->beforeRender . $this->module->id . '/' . $this->id;
>             return parent::render($view, $params);*/
>  
>         }  catch (InvalidParamException $e)
>         {
> 23. in F:\GitRepo\demo.ru\vendor\skeeks\cms\actions\ViewModelAction.php at line 111 – skeeks\cms\base\Controller::render()
> 105106107108109110111112113114115116117        {
>             return "test: test";
>         } else
>         {
>             return $this->controller->render($this->view ?: $this->id, [
>                 'model' => $this->model
>             ]);
>         }
>     }
>  
>     /**
>      *
>      * TODO: Вынести в seo компонент
> 24. in F:\GitRepo\demo.ru\vendor\skeeks\cms\actions\ViewModelActionTree.php at line 74 – skeeks\cms\actions\ViewModelAction::_go()
> 68697071727374757677                {
>                     $this->view = $this->model->treeType->code;
>                 }
>             }
>         }
>  
>         return $this->_go();
>     }
>  
> }
> 25. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Action.php at line 92 – skeeks\cms\actions\ViewModelActionTree::run()
> 26. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Action.php at line 92 – call_user_func_array:{F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Action.php:92}()
> 27. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Controller.php at line 154 – yii\base\Action::runWithParams()
> 28. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Module.php at line 454 – yii\base\Controller::runAction()
> 29. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\web\Application.php at line 84 – yii\base\Module::runAction()
> 30. in F:\GitRepo\demo.ru\vendor\yiisoft\yii2\base\Application.php at line 375 – yii\web\Application::handleRequest()
> 31. in F:\GitRepo\demo.ru\vendor\skeeks\cms\app-web.php at line 15 – yii\base\Application::run()
> 9101112131415//Определение всех неопределенных необходимых констант
> require(__DIR__ . '/global.php');
> //Стандартный загрузчик конфигов
> $config = require(__DIR__ . '/bootstrap.php');
> //$config->appendDependency(Yii::getVersion()); //Так можно подмешать чего либо к сбросу кэша
> $application = new yii\web\Application($config->getResult());
> $application->run();
> 32. in F:\GitRepo\demo.ru\frontend\web\index.php at line 45 – unknown()
> 39404142434445if (!file_exists($skeeksFile))
> {
>     //Если нет app-web.php то попробуем начать установку автоматически.
>     die("The project is not complete, not installed vendors.");
> }
>  
> include $skeeksFile;
>  $_GET = [
>     'id' => 1,
> ];
> 
> $_COOKIE = [
>     'PHPSESSID' => 'q30r9r0dovf51oafppignp3aq0',
>     '_csrf' => '4cbf46fdb86a5d4af777a932ba5084e1771cded672ef4da00805a9f7eec4de98a:2:{i:0;s:5:"_csrf";i:1;s:32:"TixZPBGvbcfVvgK_aW4Tnbxj7KYFRbPg";}',
> ];
> 
> $_SESSION = [
>     '__flash' => [],
>     'fproject\\authclient\\OAuth2_efab9532f73bd54e12ff81a83090c66ff760b62f_token' => unserialize('O:30:"fproject\\authclient\\OAuthToken":6:{s:7:"payload";O:37:"fproject\\authclient\\OAuthTokenPayload":7:{s:5:"scope";a:9:{i:0;s:6:"openid";i:1;s:4:"name";i:2;s:7:"profile";i:3;s:7:"picture";i:4;s:5:"email";i:5;s:10:"rs-pk-main";i:6;s:8:"rs-pk-so";i:7;s:11:"rs-pk-issue";i:8;s:9:"rs-pk-web";}s:3:"sub";s:43:"XpABxJgUxK7bJvugDaWiyX-azh9bJRx8e5tbsv5YnZQ";s:6:"claims";a:1:{i:0;s:5:"!5v8H";}s:6:"issuer";s:24:"http://id.projectkit.net";s:10:"expireTime";i:1458661145;s:3:"uip";N;s:8:"clientId";s:10:"cid-pk-web";}s:13:"tokenParamKey";s:12:"access_token";s:19:"tokenSecretParamKey";s:18:"oauth_token_secret";s:15:"createTimestamp";i:1458657550;s:50:"' . "\0" . 'yii\\authclient\\OAuthToken' . "\0" . '_expireDurationParamKey";s:10:"expires_in";s:34:"' . "\0" . 'yii\\authclient\\OAuthToken' . "\0" . '_params";a:6:{s:12:"access_token";s:531:"eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJYcEFCeEpnVXhLN2JKdnVnRGFXaXlYLWF6aDliSlJ4OGU1dGJzdjVZblpRIiwic2NwIjpbIm9wZW5pZCIsIm5hbWUiLCJwcm9maWxlIiwicGljdHVyZSIsImVtYWlsIiwicnMtcGstbWFpbiIsInJzLXBrLXNvIiwicnMtcGstaXNzdWUiLCJycy1way13ZWIiXSwiY2xtIjpbIiE1djhIIl0sImlzcyI6Imh0dHA6XC9cL2lkLnByb2plY3RraXQubmV0IiwiZXhwIjoxNDU4NjYxMTQ1LCJjaWQiOiJjaWQtcGstd2ViIn0.fKSXxz6olLyqtk0nEIHh0jVptoNCJC6U4E_ZSdyxzl62PdgdtKH_GnvAg4kMupoCgEeXyS09jHsBcv0YYk3BJKLAtsQUpBmyU_im5d0vS9EjStxioF85IczIX70xP8xoRrg711Fe2f_aW8yBkLDGfRx7JnFl-KEm5WxI8jRd8J0";s:13:"refresh_token";s:96:"WHBBQnhKZ1V4SzdiSnZ1Z0RhV2l5WC1hemg5YkpSeDhlNXRic3Y1WW5aUQ.Y2lkLXBrLXdlYg.yeocfK1NVP_sTgzsniTCjA";s:5:"scope";s:75:"openid name profile picture email rs-pk-main rs-pk-so rs-pk-issue rs-pk-web";s:8:"id_token";s:514:"eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJYcEFCeEpnVXhLN2JKdnVnRGFXaXlYLWF6aDliSlJ4OGU1dGJzdjVZblpRIiwiYXVkIjoiY2lkLXBrLXdlYiIsImFjciI6IjEiLCJhbXIiOlsiY291Y2hiYXNlIl0sImlzcyI6Imh0dHA6XC9cL2lkLnByb2plY3RraXQubmV0IiwibmFtZSI6IlByb2plY3RLaXQgTWFzdGVyIiwiZXhwIjoxNDU4NjU4NDQ1LCJpYXQiOjE0NTg2NTc1NDUsImVtYWlsIjoiYWRtaW5AcHJvamVjdGtpdC5uZXQifQ.Rx0zDxHoCrhTDt62BsxhVbeD2EvWjFPdchAoPouoIGnUsN2iWSa23B2LNhqyWS_DOga2Z1dn8p4z2wTI6_3qPZWnpsmqfHdETipUOfoHRZUhtEhqHvtMcMWJurFimUCjpVZJkgYTdmodXctDZmGiCwR7TGt97axOJqD3qYul84E";s:10:"token_type";s:6:"Bearer";s:10:"expires_in";i:3600;}}'),
>     '__id' => 'XpABxJgUxK7bJvugDaWiyX-azh9bJRx8e5tbsv5YnZQ',
>     'XpABxJgUxK7bJvugDaWiyX-azh9bJRx8e5tbsv5YnZQ' => unserialize('O:25:"fproject\\web\\UserIdentity":9:{s:3:"sid";s:43:"tT6RcUTWXAZTxYQ-svhMwWT4UXMYfShcTHqORUKALeo";s:3:"sub";s:43:"XpABxJgUxK7bJvugDaWiyX-azh9bJRx8e5tbsv5YnZQ";s:4:"name";s:17:"ProjectKit Master";s:8:"nickname";N;s:5:"email";s:20:"admin@projectkit.net";s:13:"emailVerified";N;s:8:"zoneinfo";N;s:6:"locale";N;s:38:"' . "\0" . 'fproject\\web\\UserIdentity' . "\0" . '_expireTime";N;}'),
>     '__returnUrl' => 'main-app/index',
>     '505092a60224b3b34502ee5b8d874fd9__id' => '1',
>     '505092a60224b3b34502ee5b8d874fd9username' => 'ProjectKit Master',
>     '505092a60224b3b34502ee5b8d874fd9__sub' => 'XpABxJgUxK7bJvugDaWiyX-azh9bJRx8e5tbsv5YnZQ',
>     '505092a60224b3b34502ee5b8d874fd9lastApp' => unserialize('O:8:"stdClass":1:{s:2:"id";s:7:"pk-home";}'),
>     'amf_storage' => unserialize('O:15:"AmfUserIdentity":11:{s:4:"role";s:16:"defaultLoginRole";s:17:"' . "\0" . 'UserIdentity' . "\0" . '_id";s:1:"1";s:18:"' . "\0" . 'UserIdentity' . "\0" . '_sub";s:43:"XpABxJgUxK7bJvugDaWiyX-azh9bJRx8e5tbsv5YnZQ";s:5:"token";s:531:"eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJYcEFCeEpnVXhLN2JKdnVnRGFXaXlYLWF6aDliSlJ4OGU1dGJzdjVZblpRIiwic2NwIjpbIm9wZW5pZCIsIm5hbWUiLCJwcm9maWxlIiwicGljdHVyZSIsImVtYWlsIiwicnMtcGstbWFpbiIsInJzLXBrLXNvIiwicnMtcGstaXNzdWUiLCJycy1way13ZWIiXSwiY2xtIjpbIiE1djhIIl0sImlzcyI6Imh0dHA6XC9cL2lkLnByb2plY3RraXQubmV0IiwiZXhwIjoxNDU4NjYxMTQ1LCJjaWQiOiJjaWQtcGstd2ViIn0.fKSXxz6olLyqtk0nEIHh0jVptoNCJC6U4E_ZSdyxzl62PdgdtKH_GnvAg4kMupoCgEeXyS09jHsBcv0YYk3BJKLAtsQUpBmyU_im5d0vS9EjStxioF85IczIX70xP8xoRrg711Fe2f_aW8yBkLDGfRx7JnFl-KEm5WxI8jRd8J0";s:8:"username";s:17:"ProjectKit Master";s:8:"password";s:531:"eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJYcEFCeEpnVXhLN2JKdnVnRGFXaXlYLWF6aDliSlJ4OGU1dGJzdjVZblpRIiwic2NwIjpbIm9wZW5pZCIsIm5hbWUiLCJwcm9maWxlIiwicGljdHVyZSIsImVtYWlsIiwicnMtcGstbWFpbiIsInJzLXBrLXNvIiwicnMtcGstaXNzdWUiLCJycy1way13ZWIiXSwiY2xtIjpbIiE1djhIIl0sImlzcyI6Imh0dHA6XC9cL2lkLnByb2plY3RraXQubmV0IiwiZXhwIjoxNDU4NjYxMTQ1LCJjaWQiOiJjaWQtcGstd2ViIn0.fKSXxz6olLyqtk0nEIHh0jVptoNCJC6U4E_ZSdyxzl62PdgdtKH_GnvAg4kMupoCgEeXyS09jHsBcv0YYk3BJKLAtsQUpBmyU_im5d0vS9EjStxioF85IczIX70xP8xoRrg711Fe2f_aW8yBkLDGfRx7JnFl-KEm5WxI8jRd8J0";s:9:"errorCode";i:0;s:12:"errorMessage";s:0:"";s:25:"' . "\0" . 'CBaseUserIdentity' . "\0" . '_state";a:2:{s:8:"username";s:17:"ProjectKit Master";s:13:"lastLoginTime";s:24:"2016-03-22T21:42:10+0700";}s:14:"' . "\0" . 'CComponent' . "\0" . '_e";N;s:14:"' . "\0" . 'CComponent' . "\0" . '_m";N;}'),
> ];
> Yii Framework
> 2016-03-22, 19:21:55
> 
> Apache/2.4.9 (Win64) PHP/5.5.12
> Yii Framework/2.0.7

**Comment by skeeks-semenov** [comment]
http://en.cms.skeeks.com/docs/install/installation-on-linux — read the 6th paragraph.

php.ini

short_open_tag on

**Comment by skeeks-semenov** [comment]
@fproject short_open_tag on

**Comment by fproject** [comment]
Thank you, it's running now!

**Comment by githubrizwan** [comment]
short_open_tag on was replace but no function

 PHP Fatal Error – yii\base\ErrorException
Call to a member function renderActiveForm() on a non-object

    1. in C:\xampp\htdocs\demo.ru\vendor\skeeks\cms-module-form2\cmsWidgets\form2\views\with-messages.php at line 72
    636465666768697071727374757677787980

            'class' => 'alert-danger sx-error-message',
            'style' => 'display: none;',
        ],
        'closeButton' => false,
        'body' => '<div class="sx-body">Ok</div>',
    ])?>
     
    <? if ($properties = $modelHasRelatedProperties->relatedProperties) : ?>
        <? foreach ($properties as $property) : ?>
            <?= $property->renderActiveForm($form, $modelHasRelatedProperties); ?>
        <? endforeach; ?>
    <? endif; ?>
     
    <?= \yii\helpers\Html::submitButton("" . \Yii::t('skeeks/form2/app', $widget->btnSubmit), [
        'class' => $widget->btnSubmitClass,
    ]); ?>
     
    <?php \skeeks\modules\cms\form2\widgets\ActiveFormConstructForm::end(); ?>

    2. yii\base\ErrorHandler::handleFatalError()

$_GET = [
    'id' => 1,
];

$_COOKIE = [
    'Phpstorm-985d67bd' => '7451fcec-d4fa-4853-9537-c4a080bd2d52',
    '__atuvc' => '3|1',
    'PHPBACKSESSID' => '777nuo7iphdo1746ql9ukuvrq4',
    '_csrf' => 'bf85ea6b3fee49b6295f6fa9239a35bc96819dd25df26185f953d5d7d46ad848a:2:{i:0;s:5:"_csrf";i:1;s:32:"zR-_JHdX4Nz-04usEa-vdrK0UAOudSRc";}',
];

**Comment by skeeks-semenov** [comment]
@githubrizwan Admin panel work?

**Comment by githubrizwan** [comment]
work after restart apache, but no loading  image this web

**Comment by skeeks-semenov** [comment]
@githubrizwan  You change the document_root Project on /frontend/web?
