### ISSUE TITLE
Роли и привилегии в админке - белый экран

### ISSUE THREAD

**Issue by yuri25** [skeeks-cms/cms#21]
В настройках в админке выбираю "Пользователи и доступ" -> Роли  В адресе браузера такое: ~sx/admin/admin-role    "Пользователи и доступ" -> Привилегии -  В адресе такое: /~sx/admin/admin-permission  
В обоих случаях отображается полностью белый экран.... Может что то настроить нужно?

**Comment by skeeks-semenov** [comment]
Это уже пофиксили, в 2.7.1 нужно обновить CMS из консоли запустить длинную команду

http://en.cms.skeeks.com/docs/update

`COMPOSER_HOME=.composer php composer.phar self-update 1.0.0-beta1 && COMPOSER_HOME=.composer php composer.phar global require "fxp/composer-asset-plugin:1.1.2" && COMPOSER_HOME=.composer php composer.phar update -o -n && php yii cms/db/dump && php yii cms/migrate --interactive=0 && php yii cms/db/refresh && php yii cms/rbac && php yii cms/cache/flush-runtimes && php yii cms/cache/flush-assets && php yii cms/utils/trigger-after-update`

**Comment by skeeks-semenov** [comment]
@yuri25

**Comment by yuri25** [comment]
Что то в конце выдало красным....

  [Composer\Downloader\TransportException]
  Could not authenticate against github.com

Вот весь процесс

You are already using composer version 1.0.0-beta1.
Changed current directory to .composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing giggsey/libphonenumber-for-php (7.2.8)
    Downloading: Connecting...    Failed to download giggsey/libphonenumber-for-php from dist: Could not authenticate against github.com
    Now trying to download from source
  - Installing giggsey/libphonenumber-for-php (7.2.8)
    Cloning 3214f7d8da6270707d8489c9fe7e691a96fb1c20

  - Removing kartik-v/yii2-widget-datepicker (v1.3.7)
  - Installing kartik-v/yii2-widget-datepicker (v1.3.9)
    Downloading: Connecting...

  [Composer\Downloader\TransportException]
  Could not authenticate against github.com

**Comment by skeeks-semenov** [comment]
@yuri25 Надо получить ключ на github и вписать его в composer.json. Иначе гитхаб не дает качать новые пакеты.

**Comment by skeeks-semenov** [comment]
`"github-oauth": {"github.com":"YOUR_KEY"}`

**Comment by skeeks-semenov** [comment]
```
"config": {
        "process-timeout": 1800,
        "discard-changes": true,
        "github-oauth": {"github.com":"YOUR_KEY"}
    }
```

**Comment by yuri25** [comment]
Добавил токен в  composer.json, все прошло успешно, но теперь на главной сайта: An internal server error occurred.  Может права пересмотреть?

**Comment by yuri25** [comment]
Точно, в процессе обновления некоторые файлы скорее всего получили пользователя и группу root и соответственно перестали выполняться от user, выполнил  sudo chown -R мой пользователь:моя группа  и все заработало, в админке роли и привилегии тоже работают, спасибо огромное за помощь.

**Comment by skeeks-semenov** [comment]
@yuri25 Написали длинную команду полностью? Не только композер ипдейт?

Может все таки какие то пакеты не установились, попробуйте отдельно команду:

> COMPOSER_HOME=.composer php composer.phar update -o -n

**Comment by yuri25** [comment]
Да, длинная команда отработала полностью, дело было в правах:) Спасибо большое

**Comment by skeeks-semenov** [comment]
@yuri25 Ах да точно, этот момент тоже часто возниакет. Перед выполнение команд обновления лучше использовать.

`sudo -su www-data`

А потом уже обновление. Ну и все теперь периодически когда бывают релизы, просто нужно выполнять эту команду. Все пакеты будут обновляться до последних версий.

**Comment by yuri25** [comment]
А не подскажете насчет "Найдены модификации ядра"  у меня при проверке системы все зеленым выделяется, только один пункт красным и там длинный список каких то записей....
Сейчас тоже красным отметило и куча записей такого вида 
/......./kareliaboard.ru/app-basic/vendor/bower/jquery:
    D package.json
/....../kareliaboard.ru/app-basic/vendor/bower/bootstrap:
    D .editorconfig
    D .gitattributes
    D .gitignore
    D .travis.yml
    D CNAME
    D CONTRIBUTING.md
    D _config.yml
    D composer.json
    D docs/LICENSE
    D docs/_data/browser-bugs.yml
    D docs/_data/core-team.yml
    D docs/_data/glyphicons.yml
    D docs/_data/sass-team.yml
    D docs/_data/showcase.yml
    D docs/_data/translations.yml
И так далее.....................................
Вот тут писал https://github.com/skeeks-cms/cms/issues/20
