### ISSUE TITLE
Error when I try to run migrations

### ISSUE THREAD

**Issue by hdushku** [skeeks-cms/cms#24]
php yii dbDumper/mysql/restore
The installation process is running the database
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '.', expecting ',' or ';''

in /home/ubuntu/workspace/app-basic/vendor/skeeks/cms-db-dumper/DbDumperComponent.php:24

Stack trace:
#0 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/di/Container.php(417): ::spl_autoload_call()
#1 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/di/Container.php(417): ReflectionClass->__construct()
#2 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/di/Container.php(360): yii\di\Container->getDependencies()
#3 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/di/Container.php(153): yii\di\Container->build()
#4 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get()
#5 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::createObject()
#6 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/di/ServiceLocator.php(71): yii\di\ServiceLocator->get()
#7 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/InlineAction.php(35): yii\di\ServiceLocator->__get()
#8 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/InlineAction.php(55): skeeks\cms\dbDumper\console\controllers\MysqlController->actionRestore()
#9 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array:{/home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/InlineAction.php:55}()
#10 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams()
#11 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction()
#12 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction()
#13 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction()
#14 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction()
#15 /home/ubuntu/workspace/app-basic/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#16 /home/ubuntu/workspace/app-basic/vendor/skeeks/cms/app-console.php(26): yii\base\Application->run()
#17 /home/ubuntu/workspace/app-basic/yii(31): ::unknown()

**Comment by skeeks-semenov** [comment]
@hdushku 

What is your version of php?
console:
`php -v`

**Comment by hdushku** [comment]
PHP 5.5.9-1ubuntu4.17 (cli)

**Comment by Shark-kun** [comment]
same problem
PHP 5.5.37-1~dotdeb+7.1 (cli) (built: Jun 24 2016 02:44:59)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
