### ISSUE TITLE
Ошибка в  "Управление настройками " в разделе пользовательские настройки

### ISSUE THREAD

**Issue by kovalenkos** [skeeks-cms/cms#26]
Здравствуйте! решил попробовать вашу замечательную cms и наткнулся на такую ошибку

Cannot use $this as parameter

 in vendor/skeeks/cms/views/admin-component-settings/users.php at line 42 

Возникает в разделе "настройки модулей" - пользовательские настройки

чтобы решить проблему (или избавиться от ошибки) надо убрать $this

'value'     => function(\skeeks\cms\models\User $model, $key, $index, $this) - было
'value'     => function(\skeeks\cms\models\User $model, $key, $index) - стало

PS

Спасибо Вам за такую хорошую работу! буду дальше изучать все ее возможности!

**Comment by skeeks-semenov** [comment]
Исправлено, забыл закрыть. Давно. Спасибо.
