### ISSUE TITLE
дополнительные свойства элемента контента

### ISSUE THREAD

**Issue by sochianton** [skeeks-cms/cms#31]
Если назвать дополнительный с тире - будет ошибка. Может предотвратить это во время того, как пользователь только создает это?
![default](https://cloud.githubusercontent.com/assets/10404619/18418343/c4e09b76-784c-11e6-8b3b-3d0e73c8ff8b.jpg)
![1](https://cloud.githubusercontent.com/assets/10404619/18418341/c4b89798-784c-11e6-8cec-58e54b9362b5.jpg)
![2](https://cloud.githubusercontent.com/assets/10404619/18418342/c4d743f0-784c-11e6-80b2-47471409ed17.jpg)

**Comment by skeeks-semenov** [comment]
Ок, доработаю
