### ISSUE TITLE
Ошибки в JavaScript коде в поведении виджета таблицы в админке

### ISSUE THREAD

**Issue by sochianton** [skeeks-cms/cms#35]
В обычном режиме, когда выделяешь в любой таблице все строки и к примеру удаляешь их, то все нормально, но как только выбрал показать больше строк(например 30) - таблица заново подгрузилась через аякс, а вот все строки уже сразу не выделяются.

**Comment by skeeks-semenov** [comment]
Да, вижу проблему, поправлю.
