### ISSUE TITLE
Дополнительные свойства ЭлементовКонтента

### ISSUE THREAD

**Issue by sochianton** [skeeks-cms/cms#38]
Когда к элементуКОнтанта добавляю свойство с типом выпадающий список (например пол: мужской и женский), то когда я его отображаю $model->relatedPropertiesModel->getSmartAttribute('gender'), отображается только второе значение (женский). Первое не отображается. Не очень хотелось править библиотеку, но ничего не придумал, как закомментировать код, показанный на рисунке. После этого все заработало

![default](https://cloud.githubusercontent.com/assets/10404619/18713920/ae8b59b0-801c-11e6-890f-cc72cc614c1a.jpg)

**Comment by skeeks-semenov** [comment]
@sochianton И еще, этот метод возвращает объект RelatedPropertyEnumModel или массив объектов RelatedPropertyEnumModel[] а не их значения.

**Comment by skeeks-semenov** [comment]
$model->relatedPropertiesModel->getEnumByAttribute('propertySex')->value

**Comment by skeeks-semenov** [comment]
$model->relatedPropertiesModel->getEnumByAttribute('propertySex')->name

**Comment by skeeks-semenov** [comment]
$model->relatedPropertiesModel->getEnumByAttribute('propertySex')->code
