### ISSUE TITLE
Error when apply migrate on fresh install

### ISSUE THREAD

**Issue by thanhpv-102** [skeeks-cms/cms#42]
I have installed by composer, and create new database for it. But when I migrate data via comment `yii cms/migrate`. It failed.
```
*** applying m150608_114030_alter_table__cms_site_code_length
    > execute SQL: ALTER TABLE {{%cms_site}} CHANGE `code` `code` CHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; ...Exception: SQLSTATE[HY000]: General error: 1833 Cannot change column 'code': used in a foreign key constraint 'cms_component_settings_site_code' of table 'skeeks.cms_component_settings'
```

**Comment by skeeks-semenov** [comment]
Yes, it is possible that migration is not established from the outset. So it has historically. Therefore it is necessary to install a ready-made image of the project. And then start the migration.

`php yii dbDumper/mysql/restore`

**Comment by thanhpv-102** [comment]
Yes. I did it. Thanks
