### ISSUE TITLE
Trying to install on c9

### ISSUE THREAD

**Issue by hdushku** [skeeks-cms/cms#47]
I just followed the instruction here:
https://cms.skeeks.com/en/docs/installation
When I run the following error shows:
PHP Notice – yii\base\ErrorException
Undefined variable: tree
![skeekserror](https://cloud.githubusercontent.com/assets/8830905/23791930/4082d076-0585-11e7-9499-63c8df7547ae.png)

**Comment by skeeks-semenov** [comment]
@hdushku 
Current documentation here. Although this is not the case.
https://docs.cms.skeeks.com/en/latest/overview.html#installation

Try to set such settings in the index.php
https://yadi.sk/i/4znPQiBc3FUFrN

`error_reporting(E_ERROR | E_WARNING | E_PARSE);
ini_set('display_errors', 'On');`

This seems to be a problem of a specific basic project.

**Comment by hdushku** [comment]
Thanks for the response
I tried what you said:
Now shows this error:
![renderactiveform](https://cloud.githubusercontent.com/assets/8830905/23831846/45285f6a-0729-11e7-96ef-885232a27b92.png)

And when I try to access admin it shows "Page not found";
![pagenotfound](https://cloud.githubusercontent.com/assets/8830905/23831851/78a40c0e-0729-11e7-8b7d-90d982fdde4f.png)

**Comment by hdushku** [comment]
Just solved by
short_open_tag on 

in php.ini
