### ISSUE TITLE
Getting unknown property: skeeks\cms\models\Tree::redirect_tree_id

### ISSUE THREAD

**Issue by Eugene-Kei** [skeeks-cms/cms#7]
Привет! 

php 7.0.2
Apache/2.4.12 
ubuntu 15.10

После установки сразу не работает. 
Выдает такую ошибку:
`Getting unknown property: skeeks\cms\models\Tree::redirect_tree_id`

```
 in /home/eugene-kie/test.local/vendor/skeeks/cms/actions/ViewModelActionTree.php at line 49 – yii\db\BaseActiveRecord::__get('redirect_tree_id')
43444546474849505152535455            ])->one();
 
            \Yii::$app->cms->setCurrentTree($treeNode);
            $this->model   = \Yii::$app->cms->getCurrentTree();
        }
 
        if ($this->model->redirect || $this->model->redirect_tree_id)
        {
            return \Yii::$app->response->redirect($this->model->url, $this->model->redirect_code);
        }
 
        //Пробуем рендерить view для текущего типа страницы
        if ($this->model)

```

**Comment by skeeks-semenov** [comment]
Надо попробовать обновиться.

**php yii cms/update**

А как устанавливали? Через композер, или просто архив качали?

**Comment by Eugene-Kei** [comment]
Обновляться пробовал. Бесполезно. И точно по инструкции ставил и с установленным глобально композером, со своими правками. Бесполезно. А еще, миграции не проходят, ошибку выдает, не помню уже какую. Начинает заливать в базу и где-то, что-то не заливается. Внешние ключи, вроде, виной.
Из коробки, не поставил, тоже, index.php там вообще не обнаружил. Уже спать хотел, долго не стал копаться.

**Comment by valetzyzy** [comment]
таже проблема, устанавливал через composer

**Comment by skeeks-semenov** [comment]
Проверю.

**Comment by valetzyzy** [comment]
Вот тебе скрин
![screenshot from 2016-02-10 21 40 20](https://cloud.githubusercontent.com/assets/3648860/12959411/eee683a6-d03e-11e5-951c-58cdd92f4ae8.png)

**Comment by skeeks-semenov** [comment]
Отключи notice в php

**Comment by valetzyzy** [comment]
отключил, заработало, но на будущее - надо пофиксить

**Comment by skeeks-semenov** [comment]
Пофиксили, и все обновили. Теперь проект должен ставиться без проблем.

**Comment by Eugene-Kei** [comment]
ночью пробовал ставить, те же ошибки

**Comment by skeeks-semenov** [comment]
Проблема с миграциями? Странно.

Попробуйте поставить из дампа **php yii cms/db/first-dump-restore**

**index.php** - в папке **frontend/web/** - лежит изначально там.

https://github.com/skeeks-cms/app-basic/tree/master/frontend/web - вот тут можно посмотреть.

**Comment by skeeks-semenov** [comment]
Можно скриншот, какие ошибки? с какими ключами?

https://yadi.sk/i/3A-OCpIpouvTa вот, только что поставил чистые миграции, все поставились успешно.

**Comment by Eugene-Kei** [comment]
Попробовал на виртуальной машине ubuntu 14 встала, но на главной куски php кода на странице торчат а админка, после авторизации выдает такую ошибку: 

> Call to a member function isActive() on a non-object

`

in /home/eugene-kei/htdocs/test.local/vendor/skeeks/cms/modules/admin/views/layouts/_admin-menu.php at line 29

                        <i class="icon icon-arrow-up" style=""></i>
                    <? endif; ?>
                    <?= $adminMenuItem->label; ?>
                </div>
 
                <? if ($subAdminMenuItems = $adminMenuItem->items) : ?>
                    <ul class="nav nav-sidebar">
                    <? foreach ($subAdminMenuItems as $subAdminMenuItem) : ?>
                        <? if ($subAdminMenuItem->isAllowShow()) : ?>
                            **<li <?= $subAdminMenuItem->isActive() ? 'class="active opened"' : '' ?>>**
                                <a href="<?= $subAdminMenuItem->getUrl() ? $subAdminMenuItem->getUrl() : "#" ?>" title="<?= $subAdminMenuItem->label; ?>" class="sx-test">
                                    <span class="sx-icon">
                                        <img src="<?= $subAdminMenuItem->getImgUrl(); ?>" />
                                    </span>
                                    <span class="txt"><?= $subAdminMenuItem->label; ?></span>
                                    <? if ($subAdminMenuItem->items) : ?>
                                        <span class="caret"></span>
                                    <? endif; ?>
                                </a>


`

**Comment by Eugene-Kei** [comment]
Из дампа ставится
А в миграциях, недочет, где-то есть.

**Comment by skeeks-semenov** [comment]
Короткие теги в настройках php надо включить. Пишу с телефона. Позже напишу точнее. И в требованиях цмс пропишу.

**Comment by Eugene-Kei** [comment]
на виртуалке встали миграции 
mysql  Ver 14.14 Distrib 5.5.47

**Comment by skeeks-semenov** [comment]
short_open_tag=On. in php.ini

**Comment by Eugene-Kei** [comment]
`*** applying m150520_183310_alter_table__cms_tree
    > execute SQL: ALTER TABLE {{%cms_tree%}} ADD `site_code` CHAR(5) NULL; ... done (time: 1.356s)
    > execute SQL: ALTER TABLE {{%cms_tree}} ADD INDEX(site_code); ... done (time: 0.175s)
    > add foreign key cms_tree_site_code: {{%cms_tree}} (site_code) references {{%cms_site}} (code) ... done (time: 1.241s)
    > execute SQL: UPDATE {{%cms_tree}}  SET `site_code` = 's1' ... done (time: 0.050s)
    > execute SQL: ALTER TABLE {{%cms_tree}} CHANGE `site_code` `site_code` CHAR(5) NOT NULL; ...Exception: SQLSTATE[HY000]: General error: 1832 Cannot change column 'site_code': used in a foreign key constraint 'cms_tree_site_code'
The SQL being executed was: ALTER TABLE `cms_tree` CHANGE `site_code` `site_code` CHAR(5) NOT NULL; (/home/eugene-kie/test.local/vendor/yiisoft/yii2/db/Schema.php:628)
#0 /home/eugene-kie/test.local/vendor/yiisoft/yii2/db/Command.php(794): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `cm...')
#1 /home/eugene-kie/test.local/vendor/yiisoft/yii2/db/Migration.php(175): yii\db\Command->execute()
#2 /home/eugene-kie/test.local/console/runtime/db-migrate/m150520_183310_alter_table__cms_tree.php(25): yii\db\Migration->execute('ALTER TABLE {{%...')
#3 /home/eugene-kie/test.local/vendor/yiisoft/yii2/db/Migration.php(93): m150520_183310_alter_table__cms_tree->safeUp()
#4 /home/eugene-kie/test.local/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(562): yii\db\Migration->up()
#5 /home/eugene-kie/test.local/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(151): yii\console\controllers\BaseMigrateController->migrateUp('m150520_183310_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /home/eugene-kie/test.local/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /home/eugene-kie/test.local/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /home/eugene-kie/test.local/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction('', Array)
#10 /home/eugene-kie/test.local/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#11 /home/eugene-kie/test.local/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate', Array)
#12 /home/eugene-kie/test.local/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate', Array)
#13 /home/eugene-kie/test.local/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /home/eugene-kie/test.local/vendor/skeeks/cms/app-console.php(27): yii\base\Application->run()
#15 /home/eugene-kie/test.local/yii(43): include('/home/eugene-ki...')
#16 {main}
*** failed to apply m150520_183310_alter_table__cms_tree (time: 2.824s)


45 from 105 migrations were applied.

Migration failed. The rest of the migrations are canceled.
`

mysql  Ver 15.1 Distrib 10.1.11-MariaDB

**Comment by Eugene-Kei** [comment]
залил из дампа. Ошибок не было. 
но сайт не работает. Подозреваю, что в 7 php дело. 

Главная:
![screenshot-test local 2016-02-17 00-31-10](https://cloud.githubusercontent.com/assets/8846973/13083014/c10e9e2a-d505-11e5-923e-9ac1b7755012.png)

Админка: 
![screenshot-test local 2016-02-17 00-35-10](https://cloud.githubusercontent.com/assets/8846973/13083085/1de7241e-d506-11e5-8ef7-1d7697ed7afa.png)

**Comment by Eugene-Kei** [comment]
ubuntu 14
PHP 5.5.9-1ubuntu4.14
mysql  Ver 14.14 Distrib 5.5.47
Работает, а не всем свеженьком не хочет )))

**Comment by skeeks-semenov** [comment]
Уфф... 

Так... дамп самый свежий? http://cms.skeeks.com/download - этот?
app-basic-1.0.2.tar.gz?

https://github.com/skeeks-cms/app-basic/blob/1.0.2/backup/db/app-basic__2016-02-15_12-52-14.sql 
- в нем уже есть redirect_tree_id и приведенные ошибки выше быть не могут )

https://yadi.sk/i/aYxTLVpAowzpP

**Comment by Eugene-Kei** [comment]
С этим дампом запустилась. Спасибо! ))

**Comment by skeeks-semenov** [comment]
Бэкапы базы лежат в проекте. В папке backup/db/

Для быстрой и более простой установки, в последней версии cms появилась команда

**php yii cms/db/first-dump-restore**

Она то и находит первый дамп из этой папки, и ставит его.

**Comment by yuri25** [comment]
php yii cms/db/first-dump-restore
 Error: Unknown command "cms/db/first-dump-restore".
Подскажите пожалуйста что за ошибка появляется?
Хотя предыдущее все отработало нормально и вот это тоже php yii cms/init
 Start initialization ...

      chmod 0777 console/runtime
      chmod 0777 common/runtime
      chmod 0777 frontend/runtime
      chmod 0777 frontend/web/assets
      chmod 0755 yii

  ... initialization completed.

Почему то с базой ошибка выскакивает....

**Comment by skeeks-semenov** [comment]
@yuri25 Многое переписал. Теперь надо использовать другую команду.

http://en.cms.skeeks.com/docs/install/installation-on-linux

Ставьте по этой инструкции.

**Comment by skeeks-semenov** [comment]
@yuri25 

`php yii cms/db/restore`

**Comment by yuri25** [comment]
О спасибо огромное!
 The installation process is running the database
Dump successfully installed

**Comment by yuri25** [comment]
Подскажите пожалуйста файловый менеджер в админке использует как то ftp? А то меня недавно ломанули через уязвимость в proftpd и я вырубил у себя на VPS  FTP сервер, т.к. я пользуюсь или sftp filezilla или ssh консоль. У меня в админке при запуске файлового менеджера выдало ошибку  "Ошибка. Не удалось соединиться с сервером".

**Comment by skeeks-semenov** [comment]
@yuri25 Нет ftp никак не используется. Если ошибка не уйдет, позже помогу разобраться.

**Comment by yuri25** [comment]
Спасибо огромное, реально крутая вещь!

**Comment by hakabe** [comment]
@skeeks-semenov 
I added "skeeks/yii2-template-cube-admin": "*" to composer.json and ran "php yii cms/update --composerVersion=1.0.0-beta1 --composerAssetPluginV=1.1.2" inside my http directory. It produces following error: 
Result : Error: Unknown command "cms/update".

**Comment by skeeks-semenov** [comment]
@hakabe 
use it: http://en.cms.skeeks.com/docs/update

```
# Composer update to the latest stable version
COMPOSER_HOME=.composer php composer.phar self-update
# Extra plug-ins
COMPOSER_HOME=.composer php composer.phar global require fxp/composer-asset-plugin --no-plugins
# Download dependency
COMPOSER_HOME=.composer php composer.phar update -o -n
# Clear all caches (Just in case)
php yii cms/cache/flush-all
# Installation of migration
php yii cms/migrate --interactive=0
# Init privilages. If the component is installed skeeks/cms-rbac (optionality)
php yii rbac/init
# Init agents. If the component is installed skeeks/cms-agent (optionality)
php yii cmsAgent/init
# Clear all caches (Just in case)
php yii cms/cache/flush-all
```

**Comment by hakabe** [comment]
@skeeks-semenov
Thanks! (I had to override git to use https and got it working).

Is there a translation file somewhere? Changing language to EN does not translate anything inside the CMS. I can assist with the translations (Finnish/English) if there's none.

**Comment by SergMSerg** [comment]
Привет! Сразу после установки запускаю Update http://en.cms.skeeks.com/docs/update
на команде 
COMPOSER_HOME=.composer php composer.phar update -o -n
получаю ошибку
[RuntimeException]
Failed to execute git clone --mirror 'git@github.com:jquery/jquery-dist.git' '/.../SkeekS/.composer/cache/vcs/git-github.com-jquery-jquery-dist.git/'

что то не так в системе/проекте или имя репозитория поменялось?

**Comment by skeeks-semenov** [comment]
@SergMSerg Отредактируйте composer.json. Добавьте в секцию config 
"config": {
        "process-timeout": 1800,
        "discard-changes": true,
        **"github-oauth": {"github.com":"your api github key"}**
    }

**Comment by SergMSerg** [comment]
Александр, та же проблема, что упоминалась выше: при запуске файлового менеджера выдало ошибку "Ошибка. Не удалось соединиться с сервером". Как наладить?
Спасибо!

**Comment by skeeks-semenov** [comment]
@SergMSerg Да, добавлю в **cms/init**, спасибо.

**Comment by javadevelopcom** [comment]
# Installation of migration
php yii cms/migrate --interactive=0

----------------------------------------------------
*** failed to apply m150520_183310_alter_table__cms_tree (time: 0.307s)


45 from 123 migrations were applied.

Migration failed. The rest of the migrations are canceled.

**Comment by javadevelopcom** [comment]
по инструкции
http://dev.cms.skeeks.com/docs/dev/ustanovka-nastroyka-konfigurirov/ustanovka-s-ispolzovaniem-composer
выдает ошибку:
[00@hosting]$ php yii cms/db/dump-list
Error: Unknown command "cms/db/dump-list".
Скачал БД (db__2016-05-28_16_49_32.sql) com.ua/www/app-basic/backup/db/
чтобы импортировать через phpMyAdmin

 Импорт успешно завершен, запросов выполнено: 535. (**db__2016-05-28_16_49_32.sql**)
### ЧТО ДЕЛАТЬ ДАЛЬШЕ?

P.S.

ls
CHANGELOG.md  _ide    composer.json  console   vendor
LICENSE       backup  composer.lock  frontend  yii
README.md     common  composer.phar  tests     yii.bat
[00@hosting]$ cd ..
[00@hosting]$ ls
LICENSE.md     composer.lock                index.php         tests
README.md      composer.phar                mail              vendor
app-basic      config                       migrations        views
assets         controllers                  models            web
commands       requirements.php  yii
composer.json     runtime           yii.bat
[00@hosting]$php yii cms/db/apply-migrations
Error: Unknown command "cms/db/apply-migrations".
[00@hosting]$php yii cms/rbac/init
Error: Unknown command "cms/rbac/init".

**Comment by skeeks-semenov** [comment]
@javadevelopcom 
Сорри, у меня бардак с документацией, никак не приведу в порядок, но актуальная версия документации тут 

http://en.cms.skeeks.com/docs/install/installation-on-linux

Там команды поменялись. Больше не планирую их менять.

`php yii dbDumper/mysql/restore`

**Comment by javadevelopcom** [comment]
[00@hosting]$ php yii dbDumper/mysql/restore
The installation process is running the database
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '.', expecting ',' or ';''

in /home/mmaspo00/app-basic/vendor/skeeks/cms-db-dumper/DbDumperComponent.php:24

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
[00@hosting]$

**Comment by skeeks-semenov** [comment]
Да, надо пересобрать проект. Ошибка написанная вами выше тоже уже исправлена.

А вам нужно попробовать перед запуском команды

`php yii dbDumper/mysql/restore`

Выполнить:

`COMPOSER_HOME=.composer php composer.phar update -o -n`

Обновить зависимости.

**Comment by javadevelopcom** [comment]
**-bash-4.1$ COMPOSER_HOME=.composer php composer.phar update -o -n**

Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to clone the git@github.com:jquery/jquery-dist.git repository, try running in interactive mode so that you can enter your GitHub credentials


  [RuntimeException]
  Failed to execute git clone --mirror 'git@github.com:jquery/jquery-dist.git
  ' '/home/mmaspo00/firepowerfight.com.ua/www/basic/demo.ru/.composer/cache/v
  cs/git-github.com-jquery-jquery-dist.git/'


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by krugozor-freelance** [comment]
Здравствуйте!
Выдаёт ошибку:
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: skeeks\cms\models\CmsTree::view_file
Подскажите, пожалуйста, что нужно сделать...

**Comment by skeeks-semenov** [comment]
Проверьте short_open_tag: on?

**Comment by krugozor-freelance** [comment]
Приветствую Вас!
Хорошего настроения!
С Уважением,- автоответчик )))...

----------------------
Подпись:
----

Студия "Кругозор-Фриланс" - создание сайтов, лендингов, досок объявлений, интернет-магазинов, качественная настройка рекламных кампаний Яндекс.Директ и Google AdWords: https://krugozor-info.ru/freelance/ 
----
"Кругозор-Хостинг" - хостинг для Ваших сайтов: https://krugozor-info.ru/host/ 
----
"Кругозор-Теремок" - интернет-магазин детской и подростковой одежды: https://krugozor-info.ru/teremok/ 
----
"Кругозор-Инфо" - доска объявлений, каталог магазинов, помощь больным детям, контекстная реклама: https://krugozor-info.ru 
----
"Кругозор-Контекст" - заработок до 100 рублей с реферала на партнёрке контекстной рекламы: https://krugozor-info.ru/kontekst/ 
----
"Золотой Круг" - система финансовой взаимопомощи.
Смотрите видеопрезентацию...
http://goldcircle-biz.com/?ref=Profits

**Comment by dima911** [comment]
Таже прблема
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: skeeks\cms\models\CmsTreeType::viewFile
Включен
short_open_tag: on
проблема сохраняется

**Comment by maslakov85** [comment]
добрый день, ставлю по инструкции

php yii cms/db/first-dump-restore
Unknown command: cms/db/first-dump-restore

и так все команды что там есть. что делать подскажите пожалуйста

**Comment by skeeks-semenov** [comment]
@maslakov85 Добрый день.

https://github.com/skeeks-cms/app-shop-smarty#install - поставьте этот базовый проект, по инструкции из readme. Должен поставиться без проблем.

**Comment by Aldifor** [comment]
Добрый день, Установил по инструкции. вышла ошибка Что делать?

**Comment by krugozor-freelance** [comment]
Приветствую Вас!
Хорошего настроения!
С Уважением,- автоответчик )))...

----------------------
Подпись:
----

Студия "Кругозор-Фриланс" - создание сайтов, лендингов, досок объявлений, интернет-магазинов, качественная настройка рекламных кампаний Яндекс.Директ и Google AdWords: https://krugozor-info.ru/freelance/ 
----
"Кругозор-Хостинг" - хостинг для Ваших сайтов: https://krugozor-info.ru/host/ 
----
"Кругозор-Теремок" - интернет-магазин детской и подростковой одежды: https://krugozor-info.ru/teremok/ 
----
"Кругозор-Инфо" - доска объявлений, каталог магазинов, помощь больным детям, контекстная реклама: https://krugozor-info.ru 
----
"Кругозор-Контекст" - заработок до 100 рублей с реферала на партнёрке контекстной рекламы: https://krugozor-info.ru/kontekst/ 
----
"Золотой Круг" - система финансовой взаимопомощи.
Смотрите видеопрезентацию...
http://goldcircle-biz.com/?ref=Profits
