### ISSUE TITLE
Проблемы при установке через composer

### ISSUE THREAD

**Issue by OrlandoST** [skeeks-cms/cms#70]
При установке пишет следующее:

> Problem 1
>     - The requested package skeeks/cms-backend * is satisfiable by skeeks/cms-backend[1.0.0-alpha, 1.0.0-alpha2, 1.0.0-alpha3, dev-master] but these conflict with your requirements or minimum-stability.
>   Problem 2
>     - The requested package skeeks/cms-backend-admin * is satisfiable by skeeks/cms-backend-admin[1.0.0-alpha, 1.0.0-alpha2, 1.0.0-alpha3, dev-master] but these conflict with your requirements or minimum-stability.
>   Problem 3
>     - The requested package skeeks/yii2-ajax-file-upload * is satisfiable by skeeks/yii2-ajax-file-upload[1.0.0-alpha, 1.0.0-alpha2, 1.0.0-alpha3, dev-master] but these conflict with your requirements or minimum-stability.

Пришлось добавить 
`"minimum-stability": "dev"`
может проблема в том что я не создавал проект композером, а склонировал git репозитарий???

**Comment by skeeks-semenov** [comment]
Какой проект копировали?
Команду какую запускали composer install или composer update? Нужна install.

**Comment by OrlandoST** [comment]
Копировал cms, запускал через install

**Comment by skeeks-semenov** [comment]
Нужно ставить один из базовых проектов, по инструкции.

https://cms.skeeks.com/marketplace/websites - любой из этих

**Comment by OrlandoST** [comment]
Благодарю.
